Daon-sy/daon-backend

src/main/java/com/daon/backend/DaonBackendApplication.java, src/main/java/com/daon/backend/config/BaseTimeEntity.java
=> ❇️[feat] : Base Time Entity 설정

src/main/java/com/daon/backend/config/BaseTimeEntity.java
createdDate -> createdAt
modifiedDate -> modifiedAt
#1
=> 🔨[refactor] : update BaseTimeEntity column

src/main/java/com/daon/backend/member/controller/MemberController.java, src/main/java/com/daon/backend/member/domain/Member.java, src/main/java/com/daon/backend/member/dto/SignInRequestDto.java, src/main/java/com/daon/backend/member/dto/SignUpRequestDto.java, src/test/java/com/daon/backend/member/controller/MemberControllerTest.java
회원 테이블에 email 컬럼 unique 설정 추가했습니다!
회원 테이블에 기본 유효성 검증 구현 추가했습니다!
=> 🔨[refactor] 컨벤션에 맞춰서 리팩토링 (회원 도메인)

src/main/java/com/daon/backend/config/WebConfig.java, src/main/java/com/daon/backend/member/controller/MemberController.java
cors allowed-origins 지정
exposed-header 지정
=> 🔧[chore] cors 설정 변경 #15

src/test/java/com/daon/backend/member/controller/MemberControllerTest.java, src/test/resources/application.yml
- 테스트 properties 추가
- 테스트 코드 수정 -> Authorization Header- 테스트 properties 추가
- 테스트 코드 수정 -> Authorization Header
=> 설정 수정에 따른 테스트 변경

src/main/java/com/daon/backend/task/domain/project/Board.java, src/main/java/com/daon/backend/task/domain/project/Project.java, src/main/java/com/daon/backend/task/domain/project/ProjectParticipant.java, src/main/java/com/daon/backend/task/domain/workspace/Division.java, src/main/java/com/daon/backend/task/domain/workspace/Profile.java, src/main/java/com/daon/backend/task/domain/workspace/Subject.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceCreator.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceParticipant.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceRepositoryImpl.java
- 엔티티 및 repository 구조 작성
- Task, TaskBookmark, ProjectRepository는 미작성. 추후 작성 예정
=> ❇️[feat] 엔티티 기본 작성 #17

src/main/java/com/daon/backend/config/security/SecurityConfig.java, src/test/java/com/daon/backend/image/controller/ImageControllerTest.java, src/test/resources/application.yml
- CORS 오류 해결
- 테스트 실패 해결 WithMockUser
=> 🐞[fix] cors 오류 해결 및 테스트 수정 #19

src/main/java/com/daon/backend/task/domain/Authority.java, src/main/java/com/daon/backend/task/domain/project/Project.java, src/main/java/com/daon/backend/task/domain/project/ProjectCreator.java, src/main/java/com/daon/backend/task/domain/project/ProjectRepository.java, src/main/java/com/daon/backend/task/domain/project/Task.java, src/main/java/com/daon/backend/task/domain/project/TaskBookmark.java, src/main/java/com/daon/backend/task/domain/project/TaskProgressStatus.java, src/main/java/com/daon/backend/task/domain/workspace/Role.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceParticipant.java
- Task, TaskBookmark 작성
- 여기까지만 작성해두겠습니다!
=> ❇️[feat] 엔티티 작성

src/main/java/com/daon/backend/common/exception/CommonExceptionHandler.java, src/main/java/com/daon/backend/member/controller/MemberController.java, src/main/java/com/daon/backend/member/controller/MemberErrorHandler.java, src/main/java/com/daon/backend/member/domain/Member.java, src/main/java/com/daon/backend/member/domain/PasswordMismatchException.java, src/main/java/com/daon/backend/member/dto/SignUpRequestDto.java, src/main/java/com/daon/backend/security/SecurityExceptionHandler.java, src/main/java/com/daon/backend/security/SecurityUtils.java, src/main/java/com/daon/backend/task/controller/ProjectController.java, src/main/java/com/daon/backend/task/controller/WorkspaceController.java, src/main/java/com/daon/backend/task/controller/WorkspaceExceptionHandler.java, src/main/java/com/daon/backend/task/domain/project/ProjectRepository.java, src/main/java/com/daon/backend/task/domain/workspace/NotWorkspaceParticipantException.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceNotFoundException.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/dto/request/CreateProjectRequestDto.java, src/main/java/com/daon/backend/task/dto/response/CreateProjectResponseDto.java, src/main/java/com/daon/backend/task/dto/response/ProjectListResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/ProjectJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/ProjectParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/ProjectRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceRepositoryImpl.java, src/main/java/com/daon/backend/task/service/ProjectService.java, src/test/java/com/daon/backend/image/controller/ImageControllerTest.java
- 프로젝트 생성, 목록 조회 개발
- 워크스페이스 오류 응답 작성
- security 오류 응답 수정
- member 오류 응답 수정
- 검증 오류 응답 추가
=> 프로젝트 생성, 목록 조회 개발 및 기타

src/main/java/com/daon/backend/member/dto/SignInRequestDto.java, src/main/java/com/daon/backend/member/dto/SignUpRequestDto.java, src/main/java/com/daon/backend/task/controller/WorkspaceController.java, src/main/java/com/daon/backend/task/controller/WorkspaceExceptionHandler.java, src/main/java/com/daon/backend/task/domain/workspace/JoinCodeMismatchException.java, src/main/java/com/daon/backend/task/domain/workspace/Profile.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceCreator.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/dto/request/CheckJoinCodeRequestDto.java, src/main/java/com/daon/backend/task/dto/request/CreateWorkspaceRequestDto.java, src/main/java/com/daon/backend/task/dto/request/JoinWorkspaceRequestDto.java, src/main/java/com/daon/backend/task/dto/response/JoinWorkspaceResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceRepositoryImpl.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
1. profile 에 email 필드 추가했습니다. #45 
2. 초대코드 로직은 추후 수정되어야 합니다. #46 
- 현재 입력받은 초대코드로 일치하는 워크스페이스를 찾게 만들어져 있습니다.
- 나중에 초대링크 도입 후 수정하겠습니다.
3. 워크스페이스 참여 로직 역시 초대링크 도입 후, 수정되어야 합니다. #47
=> [feat] Workspace 초대코드 확인 및 참여

src/main/java/com/daon/backend/member/infrastructure/WorkspaceInitManagerImpl.java, src/main/java/com/daon/backend/member/service/MemberService.java, src/main/java/com/daon/backend/member/service/WorkspaceInitManager.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceCreator.java, src/main/java/com/daon/backend/task/dto/request/CreateWorkspaceRequestDto.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
회원가입 시 개인 워크스페이스가 자동 생성됩니다. #48 
- 워크스페이스에는 제목 외의 모든 값이 null로 설정되어 있습니다.
- 제목에는 '사용자 명' + "님의 개인 워크스페이스 공간입니다." 이라는 문구가 추가됩니다.
ex) 김재윤 회원가입 -> 김재윤님의 개인 워크스페이스 공간입니다.
=> [feat] ]회원가입 시 개인 워크스페이스 생성

src/main/java/com/daon/backend/task/controller/WorkspaceController.java, src/main/java/com/daon/backend/task/controller/WorkspaceExceptionHandler.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/dto/response/FindParticipantsResponseDto.java, src/main/java/com/daon/backend/task/dto/response/FindProfileResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/WorkspaceRepositoryImpl.java, src/main/java/com/daon/backend/task/service/SameMemberExistsException.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
+++
워크스페이스에 참가 요청을 보낼 때, 해당 회원이 이미 워크스페이스의 구성원인지 확인하는 로직을 추가했습니다.
=> 그룹 워크스페이스 내 프로필 조회 / 구성원 목록 조회 

src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/dto/request/CheckJoinCodeRequestDto.java, src/main/java/com/daon/backend/task/dto/request/CreateProjectRequestDto.java, src/main/java/com/daon/backend/task/dto/request/CreateWorkspaceRequestDto.java, src/main/java/com/daon/backend/task/dto/request/JoinWorkspaceRequestDto.java, src/main/java/com/daon/backend/task/dto/response/FindParticipantsResponseDto.java, src/main/java/com/daon/backend/task/dto/response/FindProfileResponseDto.java, src/test/java/com/daon/backend/member/controller/MemberControllerTest.java, src/test/java/com/daon/backend/task/controller/ProjectControllerTest.java, src/test/java/com/daon/backend/task/controller/WorkspaceControllerTest.java
1. 워크스페이스
- 워크스페이스 생성
- 워크스페이스 목록 조회
- 워크스페이스 참여
- 워크스페이스 참여 코드 확인
- 워크스페이스 구성원 목록 조회
- 워크스페이스 프로필 조회
<br>
2. 프로젝트
- 프로젝트 생성
- 프로젝트 목록 조회
=> [Test] 워크스페이스 및 프로젝트 API 통합테스트

src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/domain/project/Board.java, src/main/java/com/daon/backend/task/domain/project/NotProjectParticipantException.java, src/main/java/com/daon/backend/task/domain/project/Project.java, src/main/java/com/daon/backend/task/domain/project/ProjectNotFoundException.java, src/main/java/com/daon/backend/task/domain/project/ProjectParticipant.java, src/main/java/com/daon/backend/task/domain/project/ProjectRepository.java, src/main/java/com/daon/backend/task/domain/project/Task.java, src/main/java/com/daon/backend/task/domain/project/TaskRepository.java, src/main/java/com/daon/backend/task/domain/workspace/Profile.java, src/main/java/com/daon/backend/task/dto/response/CreateTaskResponseDto.java, src/main/java/com/daon/backend/task/dto/response/ProjectListResponseDto.java, src/main/java/com/daon/backend/task/dto/response/TaskListResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/ProjectParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/ProjectRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/TaskJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/BoardService.java, src/main/java/com/daon/backend/task/service/TaskService.java
=> 할일 목록 조회 오류 수정

build.gradle, src/main/java/com/daon/backend/common/history/Revision.java, src/main/java/com/daon/backend/member/domain/Member.java
- 해당 기능은 Member에만 적용시켰습니다.
- 기능 개발이 끝난 후, 요구사항에 맞춰서 다른 테이블에도 적용하면 될 것 같습니다.
=> 테이블 변경 이력 (히스토리) 기본 설정

src/main/java/com/daon/backend/task/infrastructure/CheckRoleInterceptor.java
- 다른 PR merge 하면서 기존의 PR이 같이 merge 된 것 같아요 죄송합니다 ㅠ
- 하영님 피드백 반영해서 workspcae 참여자 확인 후, uri path에 projectId가 있으면 project 참여자인지 확인하는 로직으로 수정했습니다!
=> 워크스페이스 및 프로젝트 참여자 확인 인터셉터 로직 수정

src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/domain/project/ProjectRepository.java, src/main/java/com/daon/backend/task/domain/project/Task.java, src/main/java/com/daon/backend/task/domain/project/TaskNotFoundException.java, src/main/java/com/daon/backend/task/domain/project/TaskRepository.java, src/main/java/com/daon/backend/task/dto/request/SetBookmarkRequestDto.java, src/main/java/com/daon/backend/task/dto/response/SetBookmarkResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/ProjectRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/TaskBookmarkJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/TaskService.java
- 북마크 설정/해제 응답은 "created": true/false 입니다.
- 동시성 문제에 대한 부분은 공부가 필요해서 우선 기능만 구현해 둔 상태입니다. 메모해두고 공부한 뒤 추후 적용하겠습니다.
=> 북마크 설정/해제 API

src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/dto/response/FindTaskResponseDto.java, src/main/java/com/daon/backend/task/dto/response/TaskDetailResponseDto.java, src/main/java/com/daon/backend/task/dto/response/TaskListResponseDto.java, src/main/java/com/daon/backend/task/service/TaskService.java
=> 할일 상세(단건) 조회

src/main/java/com/daon/backend/task/controller/ProjectController.java, src/main/java/com/daon/backend/task/dto/project/FindProjectResponseDto.java, src/main/java/com/daon/backend/task/service/ProjectService.java
=> 프로젝트 상세(단건) 조회

src/main/java/com/daon/backend/task/controller/WorkspaceController.java, src/main/java/com/daon/backend/task/dto/workspace/FindWorkspaceResponseDto.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
=> 워크스페이스 상세(단건) 조회

src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java
=>  🐞[fix] 할 일 조회 오류 수정 #96

src/main/java/com/daon/backend/task/dto/project/FindProjectResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/BoardService.java
- 할 일 목록 조회시 담당자 지정 안되있으면 조회 안되는 오류 해결
- 프로젝트 조회시 설명 필드 담기지 않는 오류 해결
=>  🐞[fix] 오류 수정

src/main/java/com/daon/backend/task/dto/workspace/FindWorkspaceResponseDto.java
=> Fix workspace detail #155

src/main/java/com/daon/backend/task/dto/workspace/FindWorkspaceResponseDto.java, src/main/java/com/daon/backend/task/dto/workspace/ModifyRoleRequestDto.java
=> Fix: issue #157

src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/service/TaskService.java
=> ❇️[feat] 할일 삭제 #168

src/main/java/com/daon/backend/config/BaseEntity.java, src/main/java/com/daon/backend/config/JpaConfig.java, src/main/java/com/daon/backend/member/domain/Email.java, src/main/java/com/daon/backend/member/domain/Member.java, src/main/java/com/daon/backend/notification/domain/Notification.java, src/main/java/com/daon/backend/security/SecurityUtils.java, src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/domain/board/Board.java, src/main/java/com/daon/backend/task/domain/project/Project.java, src/main/java/com/daon/backend/task/domain/project/ProjectParticipant.java, src/main/java/com/daon/backend/task/domain/task/Task.java, src/main/java/com/daon/backend/task/domain/task/TaskBookmark.java, src/main/java/com/daon/backend/task/domain/task/TaskReply.java, src/main/java/com/daon/backend/task/domain/task/TaskRepository.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceParticipant.java, src/main/java/com/daon/backend/task/dto/task/history/HistoryBoard.java, src/main/java/com/daon/backend/task/dto/task/history/HistoryProjectParticipant.java, src/main/java/com/daon/backend/task/dto/task/history/TaskHistory.java, src/main/java/com/daon/backend/task/dto/task/history/TaskHistoryResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/project/ProjectParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/TaskService.java
=>  ❇️[feat] 할 일 히스토리 기능 구현 #169

src/main/java/com/daon/backend/auth/controller/AuthExceptionHandler.java, src/main/java/com/daon/backend/common/exception/CommonExceptionHandler.java, src/main/java/com/daon/backend/common/response/error/ErrorCode.java, src/main/java/com/daon/backend/common/response/error/ErrorResponse.java, src/main/java/com/daon/backend/common/response/slice/SliceResponse.java, src/main/java/com/daon/backend/image/controller/ImageErrorHandler.java, src/main/java/com/daon/backend/member/controller/MemberErrorHandler.java, src/main/java/com/daon/backend/notification/controller/NotificationExceptionHandler.java, src/main/java/com/daon/backend/security/JwtAuthenticationEntryPoint.java, src/main/java/com/daon/backend/security/SecurityExceptionHandler.java, src/main/java/com/daon/backend/task/controller/SearchController.java, src/main/java/com/daon/backend/task/controller/TaskController.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/AuthorizedExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/BoardExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/ProjectExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/SearchExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/TaskExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/TaskReplyExceptionHandler.java, src/main/java/com/daon/backend/task/controller/exceptionHandler/WorkspaceExceptionHandler.java, src/main/java/com/daon/backend/task/domain/task/TaskRepository.java, src/main/java/com/daon/backend/task/dto/task/history/TaskHistory.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/SearchService.java, src/main/java/com/daon/backend/task/service/TaskService.java
=>  ❇️[feat] Slice 공통 응답 양식 작성 #183

src/main/java/com/daon/backend/task/domain/board/Board.java, src/main/java/com/daon/backend/task/domain/board/BoardRepository.java, src/main/java/com/daon/backend/task/domain/project/Project.java, src/main/java/com/daon/backend/task/domain/project/ProjectRepository.java, src/main/java/com/daon/backend/task/domain/task/Task.java, src/main/java/com/daon/backend/task/domain/task/TaskRepository.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceParticipant.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/infrastructure/board/BoardJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/board/BoardRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/project/ProjectJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/project/ProjectRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/workspace/WorkspaceJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/workspace/WorkspaceRepositoryImpl.java, src/main/java/com/daon/backend/task/service/BoardService.java, src/main/java/com/daon/backend/task/service/ProjectService.java, src/main/java/com/daon/backend/task/service/TaskReplyService.java, src/main/java/com/daon/backend/task/service/TaskService.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
=> Refactor backend 프로젝트 (탈퇴/참여자 강퇴/삭제) 워크스페이스 (삭졔) 로직 수정

src/main/java/com/daon/backend/task/domain/task/TaskRepository.java, src/main/java/com/daon/backend/task/infrastructure/project/ProjectJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java
=>  🐞[fix] hotfix

src/main/java/com/daon/backend/task/infrastructure/task/TaskReplyJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskReplyRepositoryImpl.java, src/main/java/com/daon/backend/task/service/TaskService.java
- 댓글 목록 조회 조건 remove false 추가
- 할 일 삭제 오류 수정
=> 댓글 목록 조회, 할 일 삭제 오류 수정

src/main/java/com/daon/backend/DaonBackendApplication.java, src/main/java/com/daon/backend/notification/controller/NotificationController.java, src/main/java/com/daon/backend/notification/domain/EmitterRepository.java, src/main/java/com/daon/backend/notification/infrastructure/EmitterRepositoryImpl.java, src/main/java/com/daon/backend/notification/infrastructure/NotificationService.java, src/main/resources/application.yml
=> ❇️[feat] sse 기능 추가 #196

src/main/java/com/daon/backend/task/domain/task/Task.java, src/main/java/com/daon/backend/task/domain/task/TaskCreatedEvent.java, src/main/java/com/daon/backend/task/domain/task/TaskRemovedEvent.java, src/main/java/com/daon/backend/task/infrastructure/SendEventHandler.java
- Task 생성시, SSE Event 전송
- Task 삭제시, SSE Event 전송
=> ❇️[feat] Task SSE 추가

src/main/java/com/daon/backend/common/response/slice/PageResponse.java, src/main/java/com/daon/backend/task/controller/TaskReplyController.java, src/main/java/com/daon/backend/task/domain/task/TaskReplyRepository.java, src/main/java/com/daon/backend/task/dto/TaskSummary.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskReplyJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskReplyRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/service/TaskReplyService.java
- 할 일 목록 조회시 댓글 개수 필드 추가
- 댓글 목록 조회시, 댓글 총 개수 필드 추가
=> ❇️[feat] 댓글 개수 응답 추가

src/main/java/com/daon/backend/task/dto/TaskSummary.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java
=> ❇️[feat] 할 일 목록 응답 필드 추가

src/main/java/com/daon/backend/notification/controller/NotificationController.java, src/main/java/com/daon/backend/notification/domain/NotificationRepository.java, src/main/java/com/daon/backend/notification/dto/FindNotificationsResponse.java, src/main/java/com/daon/backend/notification/dto/NotificationSummary.java, src/main/java/com/daon/backend/notification/infrastructure/NotificationJpaRepository.java, src/main/java/com/daon/backend/notification/infrastructure/NotificationRepositoryImpl.java, src/main/java/com/daon/backend/notification/infrastructure/NotificationService.java, src/main/java/com/daon/backend/task/dto/notification/DeportationProjectAlarmResponseDto.java, src/main/java/com/daon/backend/task/dto/notification/DeportationWorkspaceAlarmResponseDto.java, src/main/java/com/daon/backend/task/dto/notification/DesignatedManagerAlarmResponseDto.java, src/main/java/com/daon/backend/task/dto/notification/InviteProjectAlarmResponseDto.java, src/main/java/com/daon/backend/task/dto/notification/InviteWorkspaceAlarmResponseDto.java
[❇️[feat] 알림 응답 발생 시간 추가]
[❇️[feat] 알림 목록 조회 API 구현]
[❇️[feat] 알림 읽음 처리 API 구현]
[❇️[feat] 알림 목록 삭제 API 구현]
[❇️[feat] 알림 SSE 응답 필드 추가]
=> Feat notifications

src/main/java/com/daon/backend/task/infrastructure/SearchQueryRepository.java, src/main/java/com/daon/backend/task/service/SearchService.java
=> 통합 검색 API 수정

src/main/java/com/daon/backend/notification/domain/Notification.java, src/main/java/com/daon/backend/notification/domain/data/Message.java, src/main/java/com/daon/backend/notification/dto/NotificationDto.java, src/main/java/com/daon/backend/task/dto/notification/SendReceiveMessageAlarmResponseDto.java, src/main/java/com/daon/backend/task/infrastructure/SendEventHandler.java
응답 양식
- notificationId
- data
- time
- workspace
- workspaceId
- workspaceTitle
- message
- messageId
- sender
- workspaceParticipantId
- name
- email
- imageUrl
- type : `RECEIVE_MESSAGE`
- read
=> 쪽지 실시간 알림 응답 수정

src/main/java/com/daon/backend/member/dto/CheckUsernameRequestDto.java, src/main/java/com/daon/backend/task/controller/TaskController.java
- 할 일 삭제 오류 수정
- 아이디 중복확인 Dto Valid 추가
=> 🐞[fix] 오류 수정

src/main/java/com/daon/backend/task/infrastructure/project/ProjectRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskRepositoryImpl.java, src/main/java/com/daon/backend/task/infrastructure/workspace/WorkspaceRepositoryImpl.java
- 목록 정렬 순서
- 워크스페이스 목록 (개인 먼저, 나머지는 이름순)
- 프로젝트 목록 이름순
- 할 일 목록 응답에 createdAt, modifiedAt 추가
=> 🔨[refactor] 워크스페이스 / 프로젝트 / 할 일 목록 정렬 순서 변경

src/main/java/com/daon/backend/config/AsyncConfig.java, src/main/java/com/daon/backend/member/infrastructure/MemberCreatedEventHandler.java, src/main/java/com/daon/backend/task/infrastructure/SendEventHandler.java, src/main/java/com/daon/backend/task/infrastructure/TaskEventHandler.java
- Eventhandler 비동기 부활..
- Async 제거하니 트랜잭션 오류로 알림 목록이 쌓이지 않음
=> 🐞[fix] hotfix

src/main/java/com/daon/backend/notification/infrastructure/NotificationSseService.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskJpaRepository.java
=> redis 설정 변경

src/main/java/com/daon/backend/task/domain/project/ProjectParticipant.java, src/main/java/com/daon/backend/task/domain/task/Task.java, src/main/java/com/daon/backend/task/domain/workspace/Workspace.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceParticipant.java, src/main/java/com/daon/backend/task/domain/workspace/WorkspaceRepository.java, src/main/java/com/daon/backend/task/infrastructure/project/ProjectParticipantJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/task/TaskJpaRepository.java, src/main/java/com/daon/backend/task/infrastructure/workspace/WorkspaceRepositoryImpl.java, src/main/java/com/daon/backend/task/service/TaskService.java, src/main/java/com/daon/backend/task/service/WorkspaceService.java
=> 회원탈퇴 오류 해결
